/**
* DictionaryApi
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.web.model


import com.squareup.moshi.Json

/**
* 
* Values: _0,_1,_2,_3,_4,_5,_6
*/

enum class DayOfWeek(val value: kotlin.Int){


    @Json(name = "0")
    _0(0),


    @Json(name = "1")
    _1(1),


    @Json(name = "2")
    _2(2),


    @Json(name = "3")
    _3(3),


    @Json(name = "4")
    _4(4),


    @Json(name = "5")
    _5(5),


    @Json(name = "6")
    _6(6);



}

