/**
* DictionaryApi
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.web.model

import android.os.Parcelable
import com.squareup.moshi.Json
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param date
 * @param temperatureC
 * @param temperatureF
 * @param summary
 */
@Parcelize

data class WeatherForecast(
    @Json(name = "date")
    val date: DateOnly? = null,
    @Json(name = "temperatureC")
    val temperatureC: kotlin.Int? = null,
    @Json(name = "temperatureF")
    val temperatureF: kotlin.Int? = null,
    @Json(name = "summary")
    val summary: kotlin.String? = null
) : Parcelable
